Repository k0rdent/kcm, pull requests merged in 2025-04, with the labels that each got.

#1349 Update capa version to v2.8.2
  templates/provider/cluster-api-provider-aws/Chart.yaml
  templates/provider/cluster-api-provider-aws/templates/provider.yaml
  templates/provider/kcm-templates/files/release.yaml
  templates/provider/kcm-templates/files/templates/cluster-api-provider-aws.yaml
Labels: test e2e

#1427 Bump sveltos to 0.52.2
  templates/provider/kcm-templates/files/release.yaml
  templates/provider/kcm-templates/files/templates/projectsveltos.yaml
  templates/provider/projectsveltos/Chart.lock
  templates/provider/projectsveltos/Chart.yaml
Labels: ksm

#1417 feat: Emit events for services
  api/v1alpha1/multiclusterservice_types.go
  internal/controller/clusterdeployment_controller.go
  internal/controller/multiclusterservice_controller.go
  internal/sveltos/status.go
Labels: enhancement, ksm
